### ISSUE TITLE
Get total message count for user

### ISSUE THREAD

**Issue by ricardobrg** [tiki/strategy_microsoft#49]
As a user I want to know the progress of my inbox indexing.
As a developer I need the total message count in the Outllok inbox.

endpoint https://graph.microsoft.com/v1.0/me/messages?$count=true

This can be used to show the estimate time to index the whole inbox.

Acceptance criteria
1 - Method that gets the total messages count by account

**Comment by NickkTMD** [comment]
expected value: 206
![Image](https://user-images.githubusercontent.com/14880163/178586168-888a551c-a398-4c2a-9c14-4b9237386526.png)



value from program:
![Image](https://user-images.githubusercontent.com/14880163/178586111-25861df9-af6d-4320-90d2-b77110da7cc4.png)
